### ISSUE TITLE
No tray icon

### ISSUE THREAD

**Issue by bam80** [flathub/org.goldendict.GoldenDict#4]
KDE Plasma, no tray icon on close (systray integration is enabled) - but the process still run

**Comment by aramgrigoryan** [comment]
I can confirm that too. And the worst thing is that i changed settings so it always starts in system tray... and now i can do nothing with the app...
please give a solution.

**Comment by proletarius101** [comment]
> I can confirm that too. And the worst thing is that i changed settings so it always starts in system tray... and now i can do nothing with the app...
> please give a solution.

PRs welcomed. Works fine in gnome.

**Comment by bam80** [comment]
I wonder if it's the same issue as with Snaps:
https://github.com/telegramdesktop/tdesktop/issues/16833

**Comment by aramgrigoryan** [comment]
> > This should be the solution:
> > `--talk-name=org.kde.StatusNotifierWatcher`
> > [telegramdesktop/tdesktop#16833 (comment)](https://github.com/telegramdesktop/tdesktop/issues/16833#issuecomment-905775805)
> 
> Can you test and confirm if this works? #8

it doesn't,, just open's the window and tries to translate the sting --talk-name=org.kde.StatusNotifierWatcher
